### ISSUE TITLE
npm install fails for v2.0.0

### ISSUE THREAD

**Issue by Zillode** [kevva/elm-bin#26]
```
$ npm install --global elm
....
> elm@2.0.0 postinstall /Users/lhoste/Libs/node-v0.12.4-darwin-x64/lib/node_modules/elm
> node lib/install.js
  ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/osx/elm-platform-osx.tar.gz response code is 404 (Not Found)
  ✖ elm pre-build test failed
```
This is because the BASE_URL uses the pkg.version (which is 2.0.0), while the git tag is defined as **v**2.0.0.

**Comment by sindikat** [comment]
On Ubuntu 15.04 I installed official packages `nodejs` and `npm`. Then I created a symbolic link `/usr/bin/nodejs` -> `/usr/bin/node`, because otherwise I couldn't install Elm platform. Then I ran `sudo npm install --global elm`, and that's what I received:

      ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
      ✖ elm pre-build test failed
      ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
      ✖ elm-make pre-build test failed
      ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
      ✖ elm-package pre-build test failed
      ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
      ✖ elm-reactor pre-build test failed
      ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
      ✖ elm-repl pre-build test failed

**Comment by cosinekitty** [comment]
I am experiencing a similar problem on Debian Wheezy (64-bit):

````
don@spearmint:~$ sudo npm install --global elm
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/bin/elm
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/bin/elm-make
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/bin/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/bin/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/bin/elm-repl
 
> elm@2.0.0 postinstall /usr/local/lib/node_modules/elm
> node lib/install.js

  ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
  ✖ elm pre-build test failed
  ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
  ✖ elm-make pre-build test failed
  ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
  ✖ elm-package pre-build test failed
  ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
  ✖ elm-reactor pre-build test failed
  ✖ https://github.com/kevva/elm-bin/raw/2.0.0/vendor/linux/x64/elm-platform-linux-x64.tar.gz response code is 404 (Not Found)
  ✖ elm-repl pre-build test failed

elm@2.0.0 /usr/local/lib/node_modules/elm
├── async-each-series@0.1.1
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
└── bin-wrapper@3.0.2 (lazy-req@1.0.0, os-filter-obj@1.0.3, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.1.2)
don@spearmint:~$ uname -a
Linux spearmint 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u2 x86_64 GNU/Linux
don@spearmint:~$ 
````

**Comment by jvoigtlaender** [comment]
That's all the same problem. After [this commit](https://github.com/kevva/elm-bin/commit/0778a568088b2344c6f242e8909a994de78e16a2), new versions of the installer should get GitHub tags without the "v", so only "2.0.0" instead of "v2.0.0". So the problems here will be fixed once someone with the appropriate rights for this repository can do a new tag/release.

**Comment by kevva** [comment]
Sorry, should be fixed now.

**Comment by cosinekitty** [comment]
I tried again. I'm seeing a different error now.  Not sure if I should open a new issue.

````
don@spearmint:~$ sudo npm install --global elm
[sudo] password for don: 
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/bin/elm
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/bin/elm-make
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/bin/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/bin/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/bin/elm-repl
 
> elm@2.0.0 postinstall /usr/local/lib/node_modules/elm
> node lib/install.js

  ✖ The `/usr/local/lib/node_modules/elm/vendor/elm` binary doesn't seem to work correctly
  ✖ elm pre-build test failed
  ✖ The `/usr/local/lib/node_modules/elm/vendor/elm-make` binary doesn't seem to work correctly
  ✖ elm-make pre-build test failed
  ✖ The `/usr/local/lib/node_modules/elm/vendor/elm-package` binary doesn't seem to work correctly
  ✖ elm-package pre-build test failed
  ✖ The `/usr/local/lib/node_modules/elm/vendor/elm-reactor` binary doesn't seem to work correctly
  ✖ elm-reactor pre-build test failed
  ✖ The `/usr/local/lib/node_modules/elm/vendor/elm-repl` binary doesn't seem to work correctly
  ✖ elm-repl pre-build test failed

elm@2.0.0 /usr/local/lib/node_modules/elm
├── async-each-series@0.1.1
├── logalot@2.1.0 (figures@1.3.5, squeak@1.2.0)
└── bin-wrapper@3.0.2 (lazy-req@1.0.0, os-filter-obj@1.0.3, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.1.2)
don@spearmint:~$ 
````

**Comment by cosinekitty** [comment]
Thanks @kevva ... that fixed it for me.  I had to use patchelf to make the elm binaries point to a local build of eglibc-2.19 because I'm running Debian Wheezy.  After that everything worked fine!

**Comment by wilhelmson** [comment]
Worked like a charm. Thanks!

**Comment by DestyNova** [comment]
Hi, this does not appear to be fixed, or at least the fix has not been pushed to the npm repositories.

```
~  ᐅ sudo npm install --global elm     
npm WARN engine get-stdin@5.0.0: wanted: {"node":">=0.12.0"} (current: {"node":"0.10.25","npm":"1.4.21"})
/usr/local/bin/elm -> /usr/local/lib/node_modules/elm/bin/elm
/usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/bin/elm-make
/usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/bin/elm-package
/usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/bin/elm-reactor
/usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/bin/elm-repl

> elm@2.0.0 postinstall /usr/local/lib/node_modules/elm
> node lib/install.js

  ✖ Invalid non-string/buffer chunk
  ✖ elm pre-build test failed
  ✖ Invalid non-string/buffer chunk
  ✖ elm-make pre-build test failed
  ✖ Response code 503 (Service Unavailable)
  ✖ elm-package pre-build test failed
  ✖ Invalid non-string/buffer chunk
  ✖ elm-reactor pre-build test failed
  ✖ Invalid non-string/buffer chunk
  ✖ elm-repl pre-build test failed

elm@2.0.0 /usr/local/lib/node_modules/elm
├── async-each-series@0.1.1
├── logalot@2.1.0 (figures@1.4.0, squeak@1.2.1)
└── bin-wrapper@3.0.2 (os-filter-obj@1.0.3, lazy-req@1.1.0, each-async@1.1.1, bin-check@2.0.0, bin-version-check@2.1.0, download@4.3.0)
```

```
~/code/elm  ᐅ elm-make --help
execvp(): No such file or directory

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
``

**Comment by shinnn** [comment]
> this does not appear to be fixed, or at least the fix has not been pushed to the npm repositories

Nope.

https://github.com/kevva/decompress/commit/7c9980cd06978481909f238d2281efa58c9b5916

**Comment by DestyNova** [comment]
Well, very curiously, I ran the same install command again (without cleaning anything up) and now:
```
  ✔ elm pre-build test passed successfully
  ✔ elm-make pre-build test passed successfully
  ✔ elm-package pre-build test passed successfully
  ✔ elm-reactor pre-build test passed successfully
  ✔ elm-repl pre-build test passed successfully
...
~/code/elm  ᐅ elm make --help
elm-make 0.2 (Elm Platform 0.15.1)

Usage: elm-make [FILES...] [--output FILE] [--yes] [--report FORMAT] [--warn]
                [--docs FILE]
  build Elm projects
...
```
I'm confused but... happy?

**Comment by celikmus** [comment]
There seems to be a discrepancy with npm's package tracker and elm's versioning...

For those who run into this issue and can not resolve, do this:
npm install -g elm@0.15.1-beta4`
